version: '3.4'

services:
  exposednode:
    container_name: exposed_node
    build:
      context: ./node_exposed
      dockerfile: ./Dockerfile 
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    restart: on-failure:5
  node_rabbit:
    container_name: node_rabbit
    build: 
      context: ./node_rabbit
      dockerfile: ./Dockerfile 
    environment:
      NODE_ENV: production
    restart: on-failure:5
  node_mongo:
    container_name: node_mongo
    build: 
      context: ./node_mongo
      dockerfile: ./Dockerfile 
    environment:
      NODE_ENV: production
    restart: on-failure:5
  rabbitmq:
    image: rabbitmq:management-alpine
    ports: 
      - 15672:15672 
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example 
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/